POST http://localhost:3001/api/table
Content-Type: application/json

{
  "number": 6,
  "name": "Bàn VIP tầng 1"
}

###
GET http://localhost:3001/api/table
###
GET http://localhost:3001/api/table?status=OCCUPIED
###
GET http://localhost:3001/api/table?search=VIP
###
GET http://localhost:3001/api/table/695ea68e124492e3ba2a5b1b
###
PUT http://localhost:3001/api/table/695ea68e124492e3ba2a5b1b
Content-Type: application/json

{
  "name": "Bàn VIP tầng 1"
}
###
DELETE http://localhost:3001/api/table/695ea68e124492e3ba2a5b1b

