POST http://localhost:3001/api/table
Content-Type: application/json

{
  "number": 11,
  "Name": "Bàn lỏ"
}

###
GET http://localhost:3001/api/table
###
GET http://localhost:3001/api/table?status=OCCUPIED
###
GET http://localhost:3001/api/table?search=VIP
###
GET http://localhost:3001/api/table/695ea705124492e3ba2a5b23
###
PUT http://localhost:3001/api/table/695f5666fd4ec837338da385
Content-Type: application/json

{
  "Name": "Bàn VIP"
}
###
DELETE http://localhost:3001/api/table/695ea5918467cb4c5939a5b8

